services:
  - type: web
    name: jules-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_RESTART
        value: "true"
      - key: RESTART_TRIGGER
        value: "ae55075"
    healthCheckPath: /healthz 