services:
  - type: web
    name: jules-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_RESTART
        value: "true"
      - key: RESTART_TRIGGER
        value: "74c35c0"
      - key: DEPLOYMENT_TIMESTAMP
        value: "2025-07-28-12-00"
    healthCheckPath: /healthz 