services:
  - type: web
    name: jules-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_RESTART
        value: "true"
      - key: RESTART_TRIGGER
        value: "6f2794a"
      - key: DEPLOYMENT_TIMESTAMP
        value: "2025-07-28-20-45"
      - key: PERSONALITY_FIX
        value: "true"
    healthCheckPath: /healthz 