services:
  - type: web
    name: jules-backend
    env: node
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /healthz 